using Microsoft.Xna.Framework;

namespace MyEngine.Core.Physics;

/// <summary>
/// The seam between "the physics simulation algorithm" and everything else (component lifecycle, the
/// fixed-timestep loop, script callbacks). MyEngine ships exactly one implementation today —
/// <see cref="ManagedPhysicsBackend2D"/>, a small self-contained impulse solver with no external
/// dependencies. Swapping in a native engine later (Bullet, PhysX) means writing one more class that
/// implements this interface, reading/writing the exact same public Rigidbody2D/Collider2D component
/// data — nothing in <see cref="PhysicsWorld2D"/>'s public API, the physics components themselves, or any
/// Editor panel needs to change. This mirrors how Godot's PhysicsServer2D decouples node-level physics
/// from a swappable server implementation.
///
/// A backend owns all simulation state itself (bodies, shapes, contacts) — <see cref="PhysicsWorld2D"/>
/// only ever holds a reference to one and forwards calls to it, translating to/from the backend-neutral
/// value types declared here (<see cref="RaycastHit2D"/>, <see cref="PhysicsEvent2D"/>).
/// </summary>
public interface IPhysicsBackend2D
{
    /// <summary>Starts simulating <paramref name="body"/>. Called automatically when a Rigidbody2D is
    /// attached to a GameObject already in a scene.</summary>
    void RegisterBody(Rigidbody2D body);

    /// <summary>Stops simulating <paramref name="body"/>. Called automatically on removal/destruction.</summary>
    void UnregisterBody(Rigidbody2D body);

    /// <summary>Starts colliding <paramref name="collider"/> against the rest of the world.</summary>
    void RegisterCollider(Collider2D collider);

    /// <summary>Stops colliding <paramref name="collider"/>.</summary>
    void UnregisterCollider(Collider2D collider);

    /// <summary>
    /// Advances the simulation by exactly one fixed step: integrates forces and velocities, detects and
    /// resolves collisions, and writes the results back onto every affected GameObject's Transform and
    /// Rigidbody2D velocities. <see cref="PhysicsWorld2D"/> calls this zero or more times per frame from
    /// a fixed-timestep accumulator — the backend itself doesn't need to know or care about frame rate.
    /// </summary>
    void Step(float fixedDeltaTime, Vector2 gravity);

    /// <summary>Casts a ray and returns the closest hit, if any.</summary>
    bool Raycast(Vector2 origin, Vector2 direction, float maxDistance, bool includeTriggers, out RaycastHit2D hit);

    /// <summary>Casts a ray and returns every hit along it, sorted nearest-first.</summary>
    IReadOnlyList<RaycastHit2D> RaycastAll(Vector2 origin, Vector2 direction, float maxDistance, bool includeTriggers);

    /// <summary>Returns every collider whose shape contains <paramref name="point"/>.</summary>
    IReadOnlyList<Collider2D> OverlapPoint(Vector2 point, bool includeTriggers);

    /// <summary>Returns every collider overlapping a circle at <paramref name="center"/>.</summary>
    IReadOnlyList<Collider2D> OverlapCircle(Vector2 center, float radius, bool includeTriggers);

    /// <summary>Collision/trigger begin-stay-end events generated by the most recent Step call. Called
    /// once per step by PhysicsWorld2D, which turns these into the OnCollisionEnter2D/OnTriggerEnter2D/etc.
    /// callbacks scripts see — the backend itself never needs to know about Component or GameObject beyond
    /// what's already reachable through Collider2D.Owner.</summary>
    IReadOnlyList<PhysicsEvent2D> ConsumeEvents();
}

/// <summary>Which begin/stay/end transition a <see cref="PhysicsEvent2D"/> represents.</summary>
public enum PhysicsEventKind
{
    CollisionEnter,
    CollisionStay,
    CollisionExit,
    TriggerEnter,
    TriggerStay,
    TriggerExit,
}

/// <summary>One backend-neutral collision/trigger event for one step. Normal/ContactPoint/RelativeVelocity
/// are only meaningful for Collision* kinds — Trigger* kinds only ever need to identify which two colliders
/// are involved.</summary>
public readonly struct PhysicsEvent2D
{
    public PhysicsEventKind Kind { get; }
    public Collider2D ColliderA { get; }
    public Collider2D ColliderB { get; }
    public Vector2 Normal { get; }
    public Vector2 ContactPoint { get; }
    public Vector2 RelativeVelocity { get; }

    public PhysicsEvent2D(
        PhysicsEventKind kind, Collider2D colliderA, Collider2D colliderB,
        Vector2 normal, Vector2 contactPoint, Vector2 relativeVelocity)
    {
        Kind = kind;
        ColliderA = colliderA;
        ColliderB = colliderB;
        Normal = normal;
        ContactPoint = contactPoint;
        RelativeVelocity = relativeVelocity;
    }
}
