using System.Security;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Xna.Framework;
using MyEngine.Core.Scripting;

namespace MyEngine.Editor.Scripting;

/// <summary>
/// Generates <c>GameScripts.csproj</c> + <c>GameScripts.sln</c> in a game project's root folder so that
/// external IDEs (VS Code with the C# extension / C# Dev Kit, Visual Studio, Rider) get real code
/// completion, go-to-definition and diagnostics while the user writes scripts.
///
/// <para><b>Why this exists.</b> <see cref="ScriptCompiler"/> compiles a project's scripts with Roslyn
/// directly (fast Play-Mode loop, no <c>dotnet build</c>), so a game project has never had a project file.
/// An IDE opening a lone <c>.cs</c> file without one has no idea that <c>Script</c>, <c>Transform</c>,
/// <c>Input</c>, <c>Vector2</c>… exist — it only knows the .NET BCL — hence no suggestions and red squiggles
/// on every engine type. A project file that references the engine assemblies is what fixes that.</para>
///
/// <para><b>What the generated project is (and isn't).</b> It exists purely as IDE metadata. The Editor
/// never builds it: Play Mode still goes through <see cref="ScriptCompiler.CompileProject"/> and shipped
/// builds through <see cref="ScriptCompiler.CompileToFile"/>. So the project mirrors that compiler's
/// settings exactly — same language version, nullable <i>off</i>, implicit usings <i>off</i> — so the IDE
/// reports the same errors the Editor's compile would, not a different set.</para>
///
/// <para><b>References</b> are only <c>MyEngine.Core</c> and <c>MonoGame.Framework</c> (plus the BCL the SDK
/// supplies). That matches what a shipped game can actually use (the Runtime references only Core); it
/// deliberately excludes Editor-only assemblies (ImGui.NET, Roslyn) that <see cref="ScriptCompiler"/>
/// happens to see in the Editor process but a built game will not have.</para>
///
/// <para><b>Regenerated on every project open.</b> The references are absolute paths to the engine
/// assemblies of the Editor version that opened the project, and the Launcher supports several installed
/// Editor versions — so the paths can legitimately change between sessions. Files are only rewritten when
/// their content differs, so a normal reopen doesn't touch timestamps or make the IDE reload.</para>
/// </summary>
public static class ScriptProjectGenerator
{
    public const string ProjectFileName = "GameScripts.csproj";
    public const string SolutionFileName = "GameScripts.sln";

    /// <summary>Written as the first line of every generated file. A file at our path *without* this
    /// marker was authored by the user, and is never overwritten.</summary>
    private const string GeneratedMarker = "AUTO-GENERATED by MyEngine";

    // Must match MyEngine.Core.csproj's <TargetFramework> — a project can only reference assemblies built
    // for the same or an older target framework.
    private const string TargetFramework = "net8.0";

    // SDK-style C# project type GUID used in .sln files.
    private const string CSharpSdkProjectTypeGuid = "9A19103F-16F7-4668-BE54-9A1E7A4F7556";

    /// <summary>Full path of the generated project file for <paramref name="projectPath"/>.</summary>
    public static string GetProjectFilePath(string projectPath) => Path.Combine(projectPath, ProjectFileName);

    /// <summary>Full path of the generated solution file for <paramref name="projectPath"/>.</summary>
    public static string GetSolutionFilePath(string projectPath) => Path.Combine(projectPath, SolutionFileName);

    /// <summary>
    /// Creates or refreshes the IDE project files for <paramref name="projectPath"/>. Returns null on
    /// success (including "nothing needed changing"), or a human-readable problem. A problem is never fatal
    /// for the Editor — scripts still compile and run without IDE support — so callers should log it, not throw.
    /// </summary>
    /// <param name="changed">True if at least one file was created or rewritten.</param>
    public static string? Ensure(string projectPath, out bool changed)
    {
        changed = false;

        var coreDll = typeof(Script).Assembly.Location;
        var monoGameDll = typeof(Vector2).Assembly.Location;
        if (string.IsNullOrEmpty(coreDll) || string.IsNullOrEmpty(monoGameDll))
        {
            // Assembly.Location is empty for single-file-published or in-memory assemblies. The Editor ships
            // as a normal folder of DLLs so this shouldn't happen, but a project file with empty
            // HintPaths would be worse than none, so say so instead.
            return "Cannot locate the engine assemblies (MyEngine.Core / MonoGame.Framework) on disk, " +
                   "so no IDE project was generated — code completion in VS Code / Visual Studio won't see engine types.";
        }

        try
        {
            Directory.CreateDirectory(projectPath);

            var problems = new List<string>();
            changed |= WriteIfChanged(GetProjectFilePath(projectPath), BuildProjectFile(coreDll, monoGameDll), problems);
            changed |= WriteIfChanged(GetSolutionFilePath(projectPath), BuildSolutionFile(projectPath), problems);

            return problems.Count == 0 ? null : string.Join(" ", problems);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return $"Could not write the IDE project files into '{projectPath}': {ex.Message}";
        }
    }

    /// <summary>Contents of <c>GameScripts.csproj</c> for the given engine assembly locations.
    /// Public so it can be unit-tested without touching disk.</summary>
    public static string BuildProjectFile(string coreDllPath, string monoGameDllPath)
    {
        var nl = Environment.NewLine;
        var sb = new StringBuilder();
        sb.Append("<Project Sdk=\"Microsoft.NET.Sdk\">").Append(nl);
        sb.Append("  <!-- ").Append(GeneratedMarker).Append(". Refreshed every time the project opens in the Editor. ")
          .Append("To customize this file yourself, remove this comment and MyEngine will stop touching it. -->").Append(nl);
        sb.Append("  <!-- This project exists only so VS Code / Visual Studio can offer code completion for your scripts. ")
          .Append("The Editor never builds it: Play Mode and Build use MyEngine's own compiler. -->").Append(nl);
        sb.Append("  <PropertyGroup>").Append(nl);
        sb.Append("    <TargetFramework>").Append(TargetFramework).Append("</TargetFramework>").Append(nl);
        sb.Append("    <OutputType>Library</OutputType>").Append(nl);
        sb.Append("    <AssemblyName>GameScripts</AssemblyName>").Append(nl);
        sb.Append("    <RootNamespace>GameScripts</RootNamespace>").Append(nl);
        // Mirror ScriptCompiler's compilation options so the IDE and the Editor agree on what is an error:
        // its ParseOptions are C# 12, and it uses default CSharpCompilationOptions (nullable and implicit
        // usings are both off).
        sb.Append("    <LangVersion>12.0</LangVersion>").Append(nl);
        sb.Append("    <Nullable>disable</Nullable>").Append(nl);
        sb.Append("    <ImplicitUsings>disable</ImplicitUsings>").Append(nl);
        sb.Append("    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>").Append(nl);
        sb.Append("    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>").Append(nl);
        sb.Append("    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>").Append(nl);
        sb.Append("    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>").Append(nl);
        sb.Append("    <NuGetAudit>false</NuGetAudit>").Append(nl);
        sb.Append("  </PropertyGroup>").Append(nl);
        sb.Append("  <ItemGroup>").Append(nl);
        // Same file set ScriptCompiler compiles: every .cs under Assets/, recursively.
        sb.Append("    <Compile Include=\"Assets/**/*.cs\" />").Append(nl);
        sb.Append("  </ItemGroup>").Append(nl);
        sb.Append("  <ItemGroup>").Append(nl);
        AppendReference(sb, "MyEngine.Core", coreDllPath, nl);
        AppendReference(sb, "MonoGame.Framework", monoGameDllPath, nl);
        sb.Append("  </ItemGroup>").Append(nl);
        sb.Append("</Project>").Append(nl);
        return sb.ToString();
    }

    private static void AppendReference(StringBuilder sb, string name, string dllPath, string nl)
    {
        sb.Append("    <Reference Include=\"").Append(name).Append("\">").Append(nl);
        sb.Append("      <HintPath>").Append(SecurityElement.Escape(dllPath)).Append("</HintPath>").Append(nl);
        // Private=false: never copy the engine DLLs next to the IDE's (unused) build output.
        sb.Append("      <Private>false</Private>").Append(nl);
        sb.Append("    </Reference>").Append(nl);
    }

    /// <summary>Contents of <c>GameScripts.sln</c>. VS Code's C# Dev Kit and Visual Studio's "open solution"
    /// flow both want a solution file; the project GUID is derived from the project's path so regenerating
    /// yields byte-identical output.</summary>
    public static string BuildSolutionFile(string projectPath)
    {
        var guid = StableProjectGuid(projectPath).ToString("B").ToUpperInvariant();
        var nl = Environment.NewLine;
        var sb = new StringBuilder();
        // The "Microsoft Visual Studio Solution File" header must stay the very first line — Visual Studio
        // rejects a solution with anything (even a comment) before it — so the marker goes right after it.
        sb.Append("Microsoft Visual Studio Solution File, Format Version 12.00").Append(nl);
        sb.Append("# Visual Studio Version 17").Append(nl);
        sb.Append("# ").Append(GeneratedMarker).Append(" - see ").Append(ProjectFileName).Append(nl);
        sb.Append("VisualStudioVersion = 17.0.31903.59").Append(nl);
        sb.Append("MinimumVisualStudioVersion = 10.0.40219.1").Append(nl);
        sb.Append("Project(\"{").Append(CSharpSdkProjectTypeGuid).Append("}\") = \"GameScripts\", \"")
          .Append(ProjectFileName).Append("\", \"").Append(guid).Append("\"").Append(nl);
        sb.Append("EndProject").Append(nl);
        sb.Append("Global").Append(nl);
        sb.Append("\tGlobalSection(SolutionConfigurationPlatforms) = preSolution").Append(nl);
        sb.Append("\t\tDebug|Any CPU = Debug|Any CPU").Append(nl);
        sb.Append("\t\tRelease|Any CPU = Release|Any CPU").Append(nl);
        sb.Append("\tEndGlobalSection").Append(nl);
        sb.Append("\tGlobalSection(ProjectConfigurationPlatforms) = postSolution").Append(nl);
        foreach (var config in new[] { "Debug", "Release" })
        {
            sb.Append('\t').Append('\t').Append(guid).Append('.').Append(config).Append("|Any CPU.ActiveCfg = ").Append(config).Append("|Any CPU").Append(nl);
            sb.Append('\t').Append('\t').Append(guid).Append('.').Append(config).Append("|Any CPU.Build.0 = ").Append(config).Append("|Any CPU").Append(nl);
        }
        sb.Append("\tEndGlobalSection").Append(nl);
        sb.Append("\tGlobalSection(SolutionProperties) = preSolution").Append(nl);
        sb.Append("\t\tHideSolutionNode = FALSE").Append(nl);
        sb.Append("\tEndGlobalSection").Append(nl);
        sb.Append("EndGlobal").Append(nl);
        return sb.ToString();
    }

    private static Guid StableProjectGuid(string projectPath)
    {
        var normalized = Path.GetFullPath(projectPath).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        // MD5 is used as a plain 16-byte deterministic mixer for an identifier here, not for security.
        return new Guid(MD5.HashData(Encoding.UTF8.GetBytes(normalized.ToLowerInvariant())));
    }

    /// <summary>Writes <paramref name="content"/> to <paramref name="path"/> unless the file already has
    /// exactly that content, or exists but wasn't generated by us (user-authored — left alone, with a note
    /// added to <paramref name="problems"/>). Returns true if the file was written.</summary>
    private static bool WriteIfChanged(string path, string content, List<string> problems)
    {
        if (File.Exists(path))
        {
            var existing = File.ReadAllText(path);
            if (existing == content) return false;

            if (!existing.Contains(GeneratedMarker, StringComparison.Ordinal))
            {
                problems.Add($"'{Path.GetFileName(path)}' already exists and wasn't generated by MyEngine, so it was left untouched " +
                             "(it must reference MyEngine.Core and MonoGame.Framework for code completion to work).");
                return false;
            }
        }

        File.WriteAllText(path, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return true;
    }
}
